"""DaddyTV channel catalog (ported from livewatch lib/data/daddylive-channels.ts).
Embed format: https://daddylive.li/embed/stream.php?id={ID}&player=1&source=tv
"""

from typing import Dict, List, Tuple

# (id, name) tuples — raw catalog from dlstreams.com
RAW_CHANNELS: List[Tuple[str, str]] = [
    ("51", "ABC USA"),
    ("206", "AHC (American Heroes Channel)"),
    ("283", "Antenna TV USA"),
    ("302", "A&E USA"),
    ("303", "AMC USA"),
    ("304", "Animal Planet"),
    ("123", "Astro SuperSport 1"),
    ("124", "Astro SuperSport 2"),
    ("125", "Astro SuperSport 3"),
    ("126", "Astro SuperSport 4"),
    ("134", "Arena Sport 1 Premium"),
    ("135", "Arena Sport 2 Premium"),
    ("139", "Arena Sport 3 Premium"),
    ("429", "Arena Sport 1 Serbia"),
    ("430", "Arena Sport 2 Serbia"),
    ("431", "Arena Sport 3 Serbia"),
    ("581", "Arena Sport 4 Serbia"),
    ("432", "Arena Sport 1 Croatia"),
    ("433", "Arena Sport 2 Croatia"),
    ("434", "Arena Sport 3 Croatia"),
    ("580", "Arena Sport 4 Croatia"),
    ("781", "Alkass One"),
    ("782", "Alkass Two"),
    ("783", "Alkass Three"),
    ("784", "Alkass Four"),
    ("579", "Arena Sport 1 BiH"),
    ("600", "Abu Dhabi Sports 1 UAE"),
    ("601", "Abu Dhabi Sports 2 UAE"),
    ("609", "Abu Dhabi Sports 1 Premium"),
    ("610", "Abu Dhabi Sports 2 Premium"),
    ("370", "Astro Cricket"),
    ("531", "Antena 3 Spain"),
    ("612", "Arena Sports Tenis Serbia"),
    ("664", "ACC Network USA"),
    ("295", "Adult Swim"),
    ("269", "A Sport PK"),
    ("717", "AXN Movies Portugal"),
    ("725", "Arte DE"),
    ("742", "AXS TV USA"),
    ("766", "ABC NY USA"),
    ("844", "Azteca 7 MX"),
    ("923", "Altitude Sports"),
    ("934", "Azteca Uno MX"),
    ("940", "Arena Sport 5 Serbia"),
    ("941", "Arena Sport 6 Serbia"),
    ("942", "Arena Sport 7 Serbia"),
    ("943", "Arena Sport 8 Serbia"),
    ("944", "Arena Sport 9 Serbia"),
    ("945", "Arena Sport 10 Serbia"),
    ("958", "Arte France"),
    ("961", "Automoto La chaine"),
    ("1000", "ATV Turkey"),
    ("1011", "A Spor Turkey"),
    ("61", "beIN Sports MENA English 1"),
    ("90", "beIN Sports MENA English 2"),
    ("91", "beIN Sports 1 Arabic"),
    ("92", "beIN Sports 2 Arabic"),
    ("93", "beIN Sports 3 Arabic"),
    ("94", "beIN Sports 4 Arabic"),
    ("95", "beIN Sports 5 Arabic"),
    ("96", "beIN Sports 6 Arabic"),
    ("97", "beIN Sports 7 Arabic"),
    ("98", "beIN Sports 8 Arabic"),
    ("99", "beIN Sports 9 Arabic"),
    ("100", "beIN SPORTS XTRA 1"),
    ("494", "beIN Sports MAX 4 France"),
    ("495", "beIN Sports MAX 5 France"),
    ("496", "beIN Sports MAX 6 France"),
    ("497", "beIN Sports MAX 7 France"),
    ("498", "beIN Sports MAX 8 France"),
    ("499", "beIN Sports MAX 9 France"),
    ("500", "beIN Sports MAX 10 France"),
    ("116", "beIN SPORTS 1 France"),
    ("117", "beIN SPORTS 2 France"),
    ("118", "beIN SPORTS 3 France"),
    ("62", "beIN SPORTS 1 Turkey"),
    ("63", "beIN SPORTS 2 Turkey"),
    ("64", "beIN SPORTS 3 Turkey"),
    ("67", "beIN SPORTS 4 Turkey"),
    ("578", "BeIN Sports HD Qatar"),
    ("425", "BeIN SPORTS USA"),
    ("372", "beIN SPORTS en Espanol"),
    ("491", "beIN SPORTS Australia 1"),
    ("492", "beIN SPORTS Australia 2"),
    ("493", "beIN SPORTS Australia 3"),
    ("522", "Barca TV Spain"),
    ("380", "Benfica TV PT"),
    ("648", "Boomerang"),
    ("476", "BNT 1 Bulgaria"),
    ("477", "BNT 2 Bulgaria"),
    ("478", "BNT 3 Bulgaria"),
    ("737", "BR Fernsehen DE"),
    ("479", "bTV Bulgaria"),
    ("481", "bTV Action Bulgaria"),
    ("484", "bTV Lady Bulgaria"),
    ("305", "BBC America (BBCA)"),
    ("306", "BET USA"),
    ("307", "Bravo USA"),
    ("349", "BBC News Channel HD"),
    ("356", "BBC One UK"),
    ("357", "BBC Two UK"),
    ("358", "BBC Three UK"),
    ("359", "BBC Four UK"),
    ("397", "BIG TEN Network (BTN USA)"),
    ("712", "beIN Sports 1 Malaysia"),
    ("713", "beIN Sports 2 Malaysia"),
    ("714", "beIN Sports 3 Malaysia"),
    ("957", "BFM TV France"),
    ("1010", "bein Sports 5 Turkey"),
    ("275", "Bandsports Brasil"),
    ("271", "Canal+ MotoGP France"),
    ("273", "Canal+ Formula 1"),
    ("280", "CW PIX 11 USA"),
    ("52", "CBS USA"),
    ("281", "Court TV USA"),
    ("300", "CW USA"),
    ("309", "CNBC USA"),
    ("310", "Comedy Central"),
    ("339", "Cartoon Network"),
    ("345", "CNN USA"),
    ("374", "Cinemax USA"),
    ("535", "Cuatro Spain"),
    ("354", "Channel 4 UK"),
    ("355", "Channel 5 UK"),
    ("308", "CBS Sports Network (CBSSN)"),
    ("121", "Canal+ France"),
    ("122", "Canal+ Sport France"),
    ("463", "Canal+ Foot France"),
    ("464", "Canal+ Sport360"),
    ("540", "Canal 11 Portugal"),
    ("48", "Canal+ Sport Poland"),
    ("73", "Canal+ Sport 2 Poland"),
    ("259", "Canal+ Sport 3 Poland"),
    ("75", "Canal+ Sport 5 Poland"),
    ("566", "Canal+ Premium Poland"),
    ("567", "Canal+ Family Poland"),
    ("570", "Canal+ Seriale Poland"),
    ("486", "Canal+ Sport 1 Afrique"),
    ("487", "Canal+ Sport 2 Afrique"),
    ("488", "Canal+ Sport 3 Afrique"),
    ("489", "Canal+ Sport 4 Afrique"),
    ("490", "Canal+ Sport 5 Afrique"),
    ("805", "CANAL 9 Denmark"),
    ("89", "Combate Brasil"),
    ("622", "Cosmote Sport 1 HD"),
    ("623", "Cosmote Sport 2 HD"),
    ("624", "Cosmote Sport 3 HD"),
    ("625", "Cosmote Sport 4 HD"),
    ("626", "Cosmote Sport 5 HD"),
    ("627", "Cosmote Sport 6 HD"),
    ("628", "Cosmote Sport 7 HD"),
    ("629", "Cosmote Sport 8 HD"),
    ("630", "Cosmote Sport 9 HD"),
    ("546", "Channel 9 Israel"),
    ("547", "Channel 10 Israel"),
    ("548", "Channel 11 Israel"),
    ("549", "Channel 12 Israel"),
    ("551", "Channel 13 Israel"),
    ("552", "Channel 14 Israel"),
    ("812", "C More First Sweden"),
    ("813", "C More Hits Sweden"),
    ("814", "C More Series Sweden"),
    ("748", "COZI TV USA"),
    ("647", "CMT USA"),
    ("602", "CTV Canada"),
    ("838", "CTV 2 Canada"),
    ("669", "Crime+ Investigation USA"),
    ("696", "Comet USA"),
    ("697", "Cooking Channel USA"),
    ("715", "Cleo TV"),
    ("750", "C SPAN 1"),
    ("767", "CBSNY USA"),
    ("776", "Chicago Sports Network"),
    ("831", "Citytv"),
    ("832", "CBC CA"),
    ("933", "Claro Sports MX"),
    ("936", "Canal5 MX"),
    ("956", "C8 France"),
    ("964", "CNews France"),
    ("1020", "Canal+ Sport CZ"),
    ("1033", "CT Sport CZ"),
    ("910", "CBS Sports Golazo"),
    ("790", "CMTV Portugal"),
    ("911", "Cytavision Sports 1 Cyprus"),
    ("912", "Cytavision Sports 2 Cyprus"),
    ("913", "Cytavision Sports 3 Cyprus"),
    ("914", "Cytavision Sports 4 Cyprus"),
    ("915", "Cytavision Sports 5 Cyprus"),
    ("916", "Cytavision Sports 6 Cyprus"),
    ("917", "Cytavision Sports 7 Cyprus"),
    ("230", "DAZN 1 UK"),
    ("285", "Discovery Velocity CA"),
    ("426", "DAZN 1 Bar DE"),
    ("427", "DAZN 2 Bar DE"),
    ("445", "DAZN 1 Spain"),
    ("446", "DAZN 2 Spain"),
    ("447", "DAZN 3 Spain"),
    ("448", "DAZN 4 Spain"),
    ("537", "DAZN F1 ES"),
    ("538", "DAZN LaLiga"),
    ("918", "DAZN Portugal FIFA Mundial de Clubes"),
    ("801", "DR1 Denmark"),
    ("802", "DR2 Denmark"),
    ("960", "DAZN Ligue 1 France"),
    ("400", "Digi Sport 1 Romania"),
    ("401", "Digi Sport 2 Romania"),
    ("402", "Digi Sport 3 Romania"),
    ("403", "Digi Sport 4 Romania"),
    ("465", "Diema Sport Bulgaria"),
    ("466", "Diema Sport 2 Bulgaria"),
    ("467", "Diema Sport 3 Bulgaria"),
    ("482", "Diema Bulgaria"),
    ("485", "Diema Family Bulgaria"),
    ("604", "Dubai Sports 1 UAE"),
    ("605", "Dubai Sports 2 UAE"),
    ("606", "Dubai Sports 3 UAE"),
    ("608", "Dubai Racing 2 UAE"),
    ("786", "DSTV Mzansi Magic"),
    ("827", "DSTV M-Net"),
    ("828", "DSTV kykNET & kie"),
    ("877", "DAZN ZONA Italy"),
    ("311", "Discovery Life Channel"),
    ("312", "Disney Channel"),
    ("313", "Discovery Channel"),
    ("657", "Discovery Family"),
    ("314", "Disney XD"),
    ("651", "Destination America"),
    ("652", "Disney JR"),
    ("348", "Dave"),
    ("44", "ESPN USA"),
    ("45", "ESPN2 USA"),
    ("316", "ESPNU USA"),
    ("379", "ESPN 1 NL"),
    ("386", "ESPN 2 NL"),
    ("71", "Eleven Sports 1 Poland"),
    ("72", "Eleven Sports 2 Poland"),
    ("428", "Eleven Sports 3 Poland"),
    ("455", "Eleven Sports 1 Portugal"),
    ("456", "Eleven Sports 2 Portugal"),
    ("457", "Eleven Sports 3 Portugal"),
    ("458", "Eleven Sports 4 Portugal"),
    ("459", "Eleven Sports 5 Portugal"),
    ("41", "EuroSport 1 Greece"),
    ("42", "EuroSport 2 Greece"),
    ("57", "EuroSport 1 Poland"),
    ("58", "EuroSport 2 Poland"),
    ("231", "Eurosport 1 SW"),
    ("232", "Eurosport 2 SW"),
    ("233", "Eurosport 1 NL"),
    ("234", "Eurosport 2 NL"),
    ("524", "EuroSport 1 Spain"),
    ("525", "EuroSport 2 Spain"),
    ("878", "EuroSport 1 Italy"),
    ("879", "EuroSport 2 Italy"),
    ("387", "ESPN Premium Argentina"),
    ("81", "ESPN Brasil"),
    ("82", "ESPN2 Brasil"),
    ("83", "ESPN3 Brasil"),
    ("85", "ESPN4 Brasil"),
    ("149", "ESPN Argentina"),
    ("150", "ESPN2 Argentina"),
    ("375", "ESPN Deportes"),
    ("288", "ESPNews"),
    ("315", "E! Entertainment Television"),
    ("363", "E4 Channel"),
    ("888", "ESPN 3 NL"),
    ("774", "ERT 1 Greece"),
    ("772", "Eurosport 1 France"),
    ("773", "Eurosport 2 France"),
    ("798", "ESPN3 Argentina"),
    ("925", "ESPN 1 MX"),
    ("926", "ESPN 2 MX"),
    ("927", "ESPN 3 MX"),
    ("928", "ESPN 4 MX"),
    ("279", "FUSE TV USA"),
    ("39", "Fox Sports 1 USA"),
    ("758", "Fox Sports 2 USA"),
    ("756", "FOX Soccer Plus"),
    ("369", "Fox Cricket"),
    ("643", "FOX Deportes USA"),
    ("820", "FOX Sports 502 AU"),
    ("821", "FOX Sports 503 AU"),
    ("822", "FOX Sports 504 AU"),
    ("823", "FOX Sports 505 AU"),
    ("824", "FOX Sports 506 AU"),
    ("825", "FOX Sports 507 AU"),
    ("929", "Fox Sports 1 MX"),
    ("930", "Fox Sports 2 MX"),
    ("931", "Fox Sports 3 MX"),
    ("787", "Fox Sports Argentina"),
    ("788", "Fox Sports 2 Argentina"),
    ("789", "Fox Sports 3 Argentina"),
    ("830", "Fox Sports Premium MX"),
    ("568", "FilmBox Premium Poland"),
    ("757", "Fight Network"),
    ("297", "Fox Business"),
    ("483", "FOX HD Bulgaria"),
    ("54", "FOX USA"),
    ("317", "FX USA"),
    ("298", "FXX USA"),
    ("301", "Freeform"),
    ("347", "Fox News"),
    ("381", "FX Movie Channel"),
    ("665", "FYI"),
    ("688", "Film4 UK"),
    ("744", "Fashion TV"),
    ("751", "FETV"),
    ("768", "FOXNY USA"),
    ("775", "Fox Weather Channel"),
    ("890", "FanDuel Sports Network Arizona"),
    ("891", "FanDuel Sports Network Detroit"),
    ("892", "FanDuel Sports Network Florida"),
    ("893", "FanDuel Sports Network Great Lakes"),
    ("894", "FanDuel Sports Network Indiana"),
    ("895", "FanDuel Sports Network Kansas City"),
    ("896", "FanDuel Sports Network Midwest"),
    ("897", "FanDuel Sports Network New Orleans"),
    ("898", "FanDuel Sports Network North"),
    ("899", "FanDuel Sports Network Ohio"),
    ("900", "FanDuel Sports Network Oklahoma"),
    ("902", "FanDuel Sports Network SoCal"),
    ("903", "FanDuel Sports Network South"),
    ("904", "FanDuel Sports Network Southeast"),
    ("905", "FanDuel Sports Network Sun"),
    ("906", "FanDuel Sports Network West"),
    ("907", "FanDuel Sports Network Wisconsin"),
    ("950", "France 2"),
    ("951", "France 3"),
    ("952", "France 4"),
    ("953", "France 5"),
    ("530", "GOL PLAY Spain"),
    ("318", "GOLF Channel USA"),
    ("319", "Game Show Network"),
    ("597", "beIN SPORTS MAX AR"),
    ("687", "Gold UK"),
    ("699", "Great American Family Channel"),
    ("743", "Galavision USA"),
    ("752", "Grit Channel"),
    ("760", "Globo SP"),
    ("761", "Globo RIO"),
    ("836", "Global CA"),
    ("320", "The Hallmark Channel"),
    ("296", "Hallmark Movies & Mysteries"),
    ("282", "Heroes & Icons USA"),
    ("321", "HBO USA"),
    ("689", "HBO2 USA"),
    ("690", "HBO Comedy USA"),
    ("691", "HBO Family USA"),
    ("692", "HBO Latino USA"),
    ("693", "HBO Signature USA"),
    ("694", "HBO Zone USA"),
    ("569", "HBO Poland"),
    ("322", "History USA"),
    ("323", "Headline News"),
    ("382", "HGTV"),
    ("846", "Happy TV Serbia"),
    ("553", "HOT3 Israel"),
    ("350", "ITV 1 UK"),
    ("351", "ITV 2 UK"),
    ("352", "ITV 3 UK"),
    ("353", "ITV 4 UK"),
    ("876", "ITV Quiz"),
    ("854", "Italia 1 Italy"),
    ("324", "Investigation Discovery USA"),
    ("325", "ION USA"),
    ("656", "IFC TV USA"),
    ("803", "Kanal 4 Denmark"),
    ("804", "Kanal 5 Denmark"),
    ("731", "Kabel Eins DE"),
    ("1001", "Kanal D Turkey"),
    ("276", "LaLigaTV UK"),
    ("278", "Law & Crime Network"),
    ("539", "LaLiga SmartBank TV"),
    ("645", "L'Equipe France"),
    ("534", "La Sexta Spain"),
    ("826", "Liverpool TV UK"),
    ("849", "Logo TV USA"),
    ("924", "Las Estrellas"),
    ("962", "LCI France"),
    ("326", "Lifetime Network"),
    ("389", "Lifetime Movies Network"),
    ("855", "La7 Italy"),
    ("856", "LA7d HD+ Italy"),
    ("136", "Match Football 1 Russia"),
    ("137", "Match Football 2 Russia"),
    ("138", "Match Football 3 Russia"),
    ("573", "Match Premier Russia"),
    ("127", "Match TV Russia"),
    ("395", "MATCH BOEC Russia"),
    ("84", "Movistar Laliga"),
    ("435", "Movistar Liga de Campeones"),
    ("436", "Movistar Deportes Spain"),
    ("438", "Movistar Deportes 2 Spain"),
    ("526", "Movistar Deportes 3 Spain"),
    ("527", "Movistar Deportes 4 Spain"),
    ("528", "Movistar Golf Spain"),
    ("563", "Motowizja Poland"),
    ("765", "MSG USA"),
    ("327", "MSNBC"),
    ("299", "Magnolia Network"),
    ("265", "M4 Sports Hungary"),
    ("437", "Movistar Supercopa de Espana"),
    ("367", "MTV UK"),
    ("371", "MTV USA"),
    ("377", "MUTV UK"),
    ("470", "M6 France"),
    ("646", "Racer TV USA"),
    ("779", "Max Sport 1 Croatia"),
    ("780", "Max Sport 2 Croatia"),
    ("770", "Marquee Sports Network"),
    ("472", "Max Sport 1 Bulgaria"),
    ("473", "Max Sport 2 Bulgaria"),
    ("474", "Max Sport 3 Bulgaria"),
    ("475", "Max Sport 4 Bulgaria"),
    ("399", "MLB Network USA"),
    ("829", "MASN USA"),
    ("654", "MY9TV USA"),
    ("661", "Discovery Turbo"),
    ("662", "METV USA"),
    ("733", "MDR DE"),
    ("749", "Mundotoro TV Spain"),
    ("778", "Monumental Sports Network"),
    ("806", "MTV Denmark"),
    ("791", "MGM+ USA / Epix"),
    ("277", "NBC10 Philadelphia"),
    ("663", "NHL Network USA"),
    ("667", "NFL RedZone"),
    ("468", "Nova Sport Bulgaria"),
    ("582", "Nova Sport Serbia"),
    ("631", "Nova Sports 1 Greece"),
    ("632", "Nova Sports 2 Greece"),
    ("633", "Nova Sports 3 Greece"),
    ("634", "Nova Sports 4 Greece"),
    ("635", "Nova Sports 5 Greece"),
    ("636", "Nova Sports 6 Greece"),
    ("599", "Nova Sports Premier League Greece"),
    ("637", "Nova Sports Start Greece"),
    ("638", "Nova Sports Prime Greece"),
    ("639", "Nova Sports News Greece"),
    ("666", "Nick Music"),
    ("762", "NESN USA"),
    ("53", "NBC USA"),
    ("404", "NBA TV USA"),
    ("777", "NBC Sports Philadelphia"),
    ("405", "NFL Network"),
    ("753", "NBC Sports Bay Area"),
    ("754", "NBC Sports Boston"),
    ("755", "NBC Sports California"),
    ("769", "NBCNY USA"),
    ("480", "Nova TV Bulgaria"),
    ("847", "Nova S Serbia"),
    ("292", "NewsNation USA"),
    ("328", "National Geographic"),
    ("329", "NICK JR"),
    ("330", "NICK"),
    ("649", "Nicktoons"),
    ("736", "NDR DE"),
    ("613", "Newsmax USA"),
    ("745", "Nat Geo Wild USA"),
    ("835", "Noovo CA"),
    ("845", "NBC Universo"),
    ("1003", "NOW TV Turkey"),
    ("611", "OnTime Sports"),
    ("541", "ONE 1 HD Israel"),
    ("542", "ONE 2 HD Israel"),
    ("439", "Orange Sport 1 Romania"),
    ("440", "Orange Sport 2 Romania"),
    ("441", "Orange Sport 3 Romania"),
    ("442", "Orange Sport 4 Romania"),
    ("331", "Oprah Winfrey Network"),
    ("332", "Oxygen True Crime"),
    ("848", "Outdoor Channel USA"),
    ("562", "Polsat Poland"),
    ("47", "Polsat Sport Poland"),
    ("50", "Polsat Sport 2 Poland"),
    ("129", "Polsat Sport 3 Poland"),
    ("443", "Polsat News Poland"),
    ("564", "Polsat Film Poland"),
    ("718", "Porto Canal Portugal"),
    ("730", "ProSieben DE"),
    ("771", "Premier Sports Ireland 1"),
    ("450", "PTV Sports"),
    ("43", "PDC TV"),
    ("88", "Premier Brasil"),
    ("583", "Prima Sport 1"),
    ("584", "Prima Sport 2"),
    ("585", "Prima Sport 3"),
    ("586", "Prima Sport 4"),
    ("334", "Paramount Network"),
    ("653", "POP TV USA"),
    ("799", "Premier Sports Ireland 2"),
    ("843", "Prima TV RO"),
    ("287", "Pac-12 Network USA"),
    ("210", "PBS USA"),
    ("293", "Reelz Channel"),
    ("364", "RTE 1"),
    ("365", "RTE 2"),
    ("119", "RMC Sport 1 France"),
    ("120", "RMC Sport 2 France"),
    ("954", "RMC Story France"),
    ("719", "RTP 1 Portugal"),
    ("720", "RTP 2 Portugal"),
    ("721", "RTP 3 Portugal"),
    ("850", "Rai 1 Italy"),
    ("851", "Rai 2 Italy"),
    ("852", "Rai 3 Italy"),
    ("853", "Rai 4 Italy"),
    ("882", "Rai Sport Italy"),
    ("858", "Rai Premium Italy"),
    ("523", "Real Madrid TV Spain"),
    ("740", "RTL DE"),
    ("839", "RDS CA"),
    ("840", "RDS 2 CA"),
    ("841", "RDS Info CA"),
    ("471", "Ring Bulgaria"),
    ("390", "RTL7 Netherland"),
    ("555", "Racing Tv UK"),
    ("607", "Rally Tv"),
    ("920", "Root Sports Northwest"),
    ("35", "Sky Sports Football UK"),
    ("36", "Sky Sports+ Plus"),
    ("37", "Sky Sports Action UK"),
    ("38", "Sky Sports Main Event"),
    ("46", "Sky Sports Tennis UK"),
    ("130", "Sky Sports Premier League"),
    ("60", "Sky Sports F1 UK"),
    ("65", "Sky Sports Cricket"),
    ("70", "Sky Sports Golf UK"),
    ("240", "Sky Sport 1 DE"),
    ("241", "Sky Sport 2 DE"),
    ("574", "Sky Sports Golf Italy"),
    ("575", "Sky Sport MotoGP Italy"),
    ("576", "Sky Sport Tennis Italy"),
    ("577", "Sky Sport F1 Italy"),
    ("366", "Sky Sports News UK"),
    ("449", "Sky Sports MIX UK"),
    ("556", "Sky Sport Top Event DE"),
    ("557", "Sky Sport Mix DE"),
    ("558", "Sky Sport Bundesliga 1 HD"),
    ("559", "Sky Sport Austria 1 HD"),
    ("759", "SportsNet New York"),
    ("460", "Sky Sport MAX Italy"),
    ("461", "Sky Sport UNO Italy"),
    ("462", "Sky Sport Arena Italy"),
    ("554", "Sky Sports Racing UK"),
    ("881", "Sky UNO Italy"),
    ("885", "SONY TEN 1"),
    ("886", "SONY TEN 2"),
    ("887", "SONY TEN 3"),
    ("946", "Sky Sport Bundesliga 2"),
    ("947", "Sky Sport Bundesliga 3"),
    ("948", "Sky Sport Bundesliga 4"),
    ("949", "Sky Sport Bundesliga 5"),
    ("965", "Sport en France"),
    ("982", "Spectrum SportsNet USA"),
    ("588", "Sky Sport 1 NZ"),
    ("589", "Sky Sport 2 NZ"),
    ("590", "Sky Sport 3 NZ"),
    ("591", "Sky Sport 4 NZ"),
    ("592", "Sky Sport 5 NZ"),
    ("593", "Sky Sport 6 NZ"),
    ("594", "Sky Sport 7 NZ"),
    ("595", "Sky Sport 8 NZ"),
    ("596", "Sky Sport 9 NZ"),
    ("587", "Sky Sport Select NZ"),
    ("49", "Sport TV1 Portugal"),
    ("74", "Sport TV2 Portugal"),
    ("289", "Sport TV4 Portugal"),
    ("454", "Sport TV3 Portugal"),
    ("290", "Sport TV5 Portugal"),
    ("291", "Sport TV6 Portugal"),
    ("722", "SIC Portugal"),
    ("385", "SEC Network USA"),
    ("78", "SporTV Brasil"),
    ("79", "SporTV2 Brasil"),
    ("80", "SporTV3 Brasil"),
    ("101", "Sport Klub 1 Croatia"),
    ("102", "Sport Klub 2 Croatia"),
    ("103", "Sport Klub 3 Croatia"),
    ("104", "Sport Klub 4 Croatia"),
    ("453", "Sport Klub HD Croatia"),
    ("406", "Sportsnet Ontario"),
    ("411", "Sportsnet One"),
    ("407", "Sportsnet West"),
    ("408", "Sportsnet East"),
    ("409", "Sportsnet 360"),
    ("410", "Sportsnet World"),
    ("412", "SuperSport Grandstand"),
    ("413", "SuperSport PSL"),
    ("414", "SuperSport Premier league"),
    ("415", "SuperSport LaLiga"),
    ("416", "SuperSport Variety 1"),
    ("417", "SuperSport Variety 2"),
    ("418", "SuperSport Variety 3"),
    ("419", "SuperSport Variety 4"),
    ("420", "SuperSport Action"),
    ("421", "SuperSport Rugby"),
    ("422", "SuperSport Golf"),
    ("423", "SuperSport Tennis"),
    ("424", "SuperSport Motorsport"),
    ("56", "Supersport Football"),
    ("368", "SuperSport Cricket"),
    ("572", "SuperSport MaXimo 1"),
    ("716", "Sporting TV Portugal"),
    ("571", "SportDigital Fussball"),
    ("764", "Spectrum Sportsnet LA"),
    ("640", "Sportdigital1+ Germany"),
    ("641", "Sport1 Germany"),
    ("670", "S4C UK"),
    ("710", "Sport KLUB Golf Croatia"),
    ("729", "SAT.1 DE"),
    ("671", "Sky Cinema Premiere UK"),
    ("672", "Sky Cinema Select UK"),
    ("673", "Sky Cinema Hits UK"),
    ("674", "Sky Cinema Greats UK"),
    ("675", "Sky Cinema Animation UK"),
    ("676", "Sky Cinema Family UK"),
    ("677", "Sky Cinema Action UK"),
    ("678", "Sky Cinema Comedy UK"),
    ("679", "Sky Cinema Thriller UK"),
    ("680", "Sky Cinema Drama UK"),
    ("681", "Sky Cinema Sci-Fi Horror UK"),
    ("695", "Showtime SHOxBET USA"),
    ("811", "SEE Denmark"),
    ("859", "Sky Cinema Collection Italy"),
    ("860", "Sky Cinema Uno Italy"),
    ("861", "Sky Cinema Action Italy"),
    ("862", "Sky Cinema Comedy Italy"),
    ("863", "Sky Cinema Uno +24 Italy"),
    ("864", "Sky Cinema Romance Italy"),
    ("865", "Sky Cinema Family Italy"),
    ("866", "CW Philly"),
    ("867", "Sky Cinema Drama Italy"),
    ("868", "Sky Cinema Suspense Italy"),
    ("869", "Sky Sport 24 Italy"),
    ("870", "Sky Sport Calcio Italy"),
    ("871", "Sky Calcio 1 Italy"),
    ("872", "Sky Calcio 2 Italy"),
    ("873", "Sky Calcio 3 Italy"),
    ("874", "Sky Calcio 4 Italy"),
    ("875", "Sky Sport Basket Italy"),
    ("880", "Sky Serie Italy"),
    ("284", "StarzPlay CricLife 1 HD"),
    ("682", "Sky Showcase UK"),
    ("683", "Sky Arts UK"),
    ("684", "Sky Comedy UK"),
    ("685", "Sky Crime"),
    ("686", "Sky History"),
    ("708", "Sky MAX UK"),
    ("614", "SSC Sport 1"),
    ("615", "SSC Sport 2"),
    ("616", "SSC Sport 3"),
    ("617", "SSC Sport 4"),
    ("618", "SSC Sport 5"),
    ("619", "SSC Sport Extra 1"),
    ("620", "SSC Sport Extra 2"),
    ("621", "SSC Sport Extra 3"),
    ("140", "Sport 1 Israel"),
    ("141", "Sport 2 Israel"),
    ("142", "Sport 3 Israel"),
    ("143", "Sport 4 Israel"),
    ("144", "Sport 5 Israel"),
    ("145", "Sport 5 PLUS Israel"),
    ("146", "Sport 5 Live Israel"),
    ("147", "Sport 5 Star Israel"),
    ("148", "Sport 5 Gold Israel"),
    ("294", "Science Channel"),
    ("333", "Showtime USA"),
    ("335", "Starz"),
    ("361", "Sky Witness HD"),
    ("732", "Sixx DE"),
    ("362", "Sky Atlantic"),
    ("373", "SYFY USA"),
    ("658", "Sundance TV"),
    ("735", "SWR DE"),
    ("738", "SUPER RTL DE"),
    ("739", "SR Fernsehen DE"),
    ("785", "Sky Sports Golf DE"),
    ("603", "Smithsonian Channel"),
    ("274", "Sky Sports F1 DE"),
    ("884", "Sky Sports Tennis DE"),
    ("883", "SBS6 NL"),
    ("267", "Star Sports 1 IN"),
    ("268", "Star Sports Hindi IN"),
    ("792", "Showtime 2 USA"),
    ("793", "Showtime Showcase USA"),
    ("794", "Showtime Extreme USA"),
    ("795", "Showtime Family Zone USA"),
    ("796", "Showtime Next USA"),
    ("797", "Showtime Women USA"),
    ("921", "Space City Home Network"),
    ("922", "SportsNet Pittsburgh"),
    ("1002", "Show TV Turkey"),
    ("1004", "Star TV Turkey"),
    ("31", "TNT Sports 1 UK"),
    ("32", "TNT Sports 2 UK"),
    ("33", "TNT Sports 3 UK"),
    ("34", "TNT Sports 4 UK"),
    ("111", "TSN1"),
    ("112", "TSN2"),
    ("113", "TSN3"),
    ("114", "TSN4"),
    ("115", "TSN5"),
    ("565", "TVN HD Poland"),
    ("444", "TVN24 Poland"),
    ("560", "TVP1 Poland"),
    ("561", "TVP2 Poland"),
    ("532", "Telecinco Spain"),
    ("533", "TVE La 1 Spain"),
    ("536", "TVE La 2 Spain"),
    ("723", "TVI Portugal"),
    ("724", "TVI Reality Portugal"),
    ("529", "Teledeporte Spain"),
    ("746", "TYC Sports Argentina"),
    ("128", "TVP Sport Poland"),
    ("87", "TNT Brasil"),
    ("388", "TNT Sports Argentina"),
    ("642", "TNT Sports HD Chile"),
    ("40", "Tennis Channel"),
    ("741", "Ten Sports PK"),
    ("66", "TUDN USA"),
    ("131", "Telemundo"),
    ("336", "TBS USA"),
    ("337", "TLC"),
    ("338", "TNT USA"),
    ("469", "TF1 France"),
    ("833", "TVA Sports"),
    ("834", "TVA Sports 2"),
    ("932", "TVC Deportes MX"),
    ("935", "TUDN MX"),
    ("955", "TMC France"),
    ("340", "Travel Channel"),
    ("341", "TruTV USA"),
    ("342", "TVLAND"),
    ("644", "TCM USA"),
    ("698", "TMC Channel USA"),
    ("384", "The Food Network"),
    ("394", "The Weather Channel"),
    ("452", "TVP INFO"),
    ("650", "TeenNick"),
    ("660", "TV ONE USA"),
    ("807", "TV2 Bornholm Denmark"),
    ("808", "TV2 Sport X Denmark"),
    ("809", "TV3 Sport Denmark"),
    ("810", "TV2 Sport Denmark"),
    ("817", "TV2 Denmark"),
    ("818", "TV2 Zulu"),
    ("819", "TV3+ Denmark"),
    ("842", "TVO CA"),
    ("1005", "TV8 Turkey"),
    ("700", "TV4 Hockey"),
    ("223", "TV3 Max Denmark"),
    ("270", "T Sports BD"),
    ("701", "TV4 Tennis"),
    ("702", "TV4 Motor"),
    ("703", "TV4 Sport Live 1"),
    ("704", "TV4 Sport Live 2"),
    ("705", "TV4 Sport Live 3"),
    ("706", "TV4 Sport Live 4"),
    ("707", "TV4 Sportkanalen"),
    ("747", "TV4 Football Sweden"),
    ("709", "Tennis+ 10"),
    ("711", "Tennis+ 12"),
    ("889", "TRT Spor TR"),
    ("343", "USA Network"),
    ("668", "Universal Kids USA"),
    ("132", "Univision"),
    ("133", "Unimas"),
    ("451", "Viaplay Sports 1 UK"),
    ("550", "Viaplay Sports 2 UK"),
    ("521", "#Vamos Spain"),
    ("815", "V Film Premiere"),
    ("816", "V Film Family"),
    ("260", "Vodafone Sport"),
    ("272", "V Sport Motor Sweden"),
    ("344", "VH1 USA"),
    ("378", "Veronica NL"),
    ("391", "VTV+ Uruguay"),
    ("659", "VICE TV"),
    ("346", "Willow Cricket"),
    ("598", "Willow 2 Cricket"),
    ("376", "WWE Network"),
    ("392", "Win Sports+ Columbia"),
    ("655", "WETV USA"),
    ("734", "WDR DE"),
    ("959", "W9 France"),
    ("286", "YTV CA"),
    ("763", "YES Network USA"),
    ("543", "Yes Movies Action Israel"),
    ("544", "Yes Movies Kids Israel"),
    ("545", "Yes Movies Comedy Israel"),
    ("837", "Yes TV CA"),
    ("393", "Ziggo Sport NL"),
    ("398", "Ziggo Sport 2 NL"),
    ("919", "Ziggo Sport 3 NL"),
    ("396", "Ziggo Sport 4 NL"),
    ("383", "Ziggo Sport 5 NL"),
    ("901", "Ziggo Sport 6 NL"),
    ("727", "ZDF DE"),
    ("728", "ZDF Info DE"),
    ("963", "6ter France"),
    ("857", "20 Mediaset Italy"),
    ("800", "6'eren Denmark"),
    ("360", "5 USA"),
    ("726", "3sat DE"),
    ("970", "Starz Cinema"),
    ("971", "Starz Comedy"),
    ("972", "Starz Edge"),
    ("973", "Starz In Black"),
    ("974", "Starz Kids & Family"),
    ("975", "Starz Encore"),
    ("976", "Starz Encore Action"),
    ("977", "Starz Encore Black"),
    ("978", "Starz Encore Classic"),
    ("979", "Starz Encore Family"),
    ("980", "Starz Encore Suspense"),
    ("981", "Starz Encore Westerns"),
]


# ─────────────────────────────────────────────────────────────────────
# Categorization (ported 1-to-1 from livewatch lib/data/daddylive-channels.ts)
# ─────────────────────────────────────────────────────────────────────
def _categorize(name: str) -> Dict[str, str]:
    n = name.lower()
    country = "International"
    if (
        "france" in n or " fr" in n
        or any(k in n for k in [
            "tf1","m6","c8","w9","tmc","arte france","bfm","canal+","rmc",
            "eurosport 1 france","eurosport 2 france","dazn ligue","l'equipe",
            "lci","cnews","6ter","automoto","sport en france","rmc story",
        ])
    ):
        country = "France"
    elif (
        "uk" in n or "england" in n
        or any(k in n for k in [
            "sky sports","tnt sports","bbc","itv","channel 4","channel 5","dave",
            "sky cinema","sky witness","sky atlantic","sky showcase","sky arts",
            "sky comedy","sky crime","sky history","sky max","viaplay sports",
            "laliga tv uk","racing tv","s4c","gold","film4","5 usa","sky news",
            "mutv","dazn 1 uk","premier sports ireland",
        ])
    ):
        country = "UK"
    elif (
        "spain" in n
        or ("es" in n and "dazn" in n)
        or any(k in n for k in [
            "movistar","telecinco","tve la","la sexta","cuatro","antena 3 spain",
            "gol play","teledeporte","#vamos","real madrid tv","barca tv",
            "mundotoro","laliga smart",
        ])
    ):
        country = "Spain"
    elif (
        "portugal" in n or " pt" in n
        or any(k in n for k in [
            "sport tv","benfica","sporting tv","porto canal",
            "eleven sports 1 portugal","eleven sports 2 portugal","eleven sports 3 portugal",
            "eleven sports 4 portugal","eleven sports 5 portugal",
            "rtp","sic","tvi","axn movies portugal","canal 11 portugal","cmtv portugal","dazn portugal",
        ])
    ):
        country = "Portugal"
    elif (
        "italy" in n or " it" in n
        or any(k in n for k in [
            "rai ","canale 5","italia 1","la7","sky sport calcio","sky sport uno",
            "sky sport arena","sky sport max","sky sport 24","sky calcio",
            "sky cinema collection","sky cinema uno","sky cinema action",
            "sky cinema comedy","sky cinema romance","sky cinema family",
            "sky cinema drama","sky cinema suspense","sky serie","sky uno",
            "dazn zona","20 mediaset","eurosport 1 italy","eurosport 2 italy",
            "rai sport","rai premium","sky sport basket","sky sport golf italy",
            "sky sport motogp","sky sport tennis italy","sky sport f1 italy",
        ])
    ):
        country = "Italy"
    elif (
        "germany" in n or " de" in n
        or any(k in n for k in [
            "sky sport 1 de","sky sport 2 de","dazn 1 bar","dazn 2 bar",
            "sky sport bundesliga","sky sport top event","sky sport mix de",
            "rtl de","sat.1","prosieben","kabel eins","sixx","super rtl",
            "zdf","3sat","ard","br fernsehen","mdr","ndr","swr","sr fernsehen",
            "wdr","arte de","sport1 germany","sportdigital",
            "sky sports f1 de","sky sports golf de","sky sports tennis de",
        ])
    ):
        country = "Germany"
    elif (
        "usa" in n
        or ("network" in n and "sport" not in n)
        or any(k in n for k in [
            "abc usa","cbs usa","nbc usa","fox usa","espn usa","espn2 usa","espnu",
            "fox sports 1 usa","fox sports 2 usa","nba tv","nfl network","nfl redzone",
            "mlb network","nhl network","tennis channel","golf channel","sec network",
            "acc network","big ten","pac-12","cnn usa","msnbc","fox news","cnbc usa",
            "headline news","abc ny","cbsny","nbcny","foxny","tbs usa","tnt usa",
            "cw usa","pix 11","court tv","fuse tv","newsmax","newsnation",
            "hbo","showtime","starz","cinemax","fx usa","fxx","freeform","amc usa",
            "a&e usa","bravo usa","e! entertainment","syfy usa","usa network",
            "discovery channel","tlc","hgtv","history usa","lifetime","hallmark",
            "bet usa","comedy central","mtv usa","cartoon network","nick",
            "disney channel","animal planet","espnews","espn deportes","ion usa",
            "paramount network","pop tv","travel channel","trutv","tvland",
            "tcm usa","metv","adult swim","fyi","game show","reelz",
            "investigation discovery","magnolia","oprah","oxygen","science channel",
            "sundance","discovery life","discovery family","destination america",
            "disney xd","disney jr","nick jr","nicktoons","boomerang",
            "universal kids","logo tv","cozi tv","grit","comet","cooking channel",
            "cleo tv","crime+","vice tv","fetv","discovery turbo","fx movie",
            "axs tv","weather channel","c span","smithsonian","pbs usa","law & crime",
            "heroes & icons","my9tv","fanduel","spectrum sports","marquee sports",
            "monumental sports","sportsnet new york","msg usa","nesn usa","nbc sports",
            "root sports","altitude sports","chicago sports","space city","yes network",
        ])
    ):
        country = "USA"
    elif "poland" in n or " pl" in n or any(k in n for k in [
        "polsat","canal+ sport poland","canal+ sport 2 poland","canal+ sport 3 poland",
        "canal+ sport 5 poland","canal+ premium poland","canal+ family poland",
        "canal+ seriale","canal+ extra","eleven sports 1 poland","eleven sports 2 poland",
        "eleven sports 3 poland","eleven sports 4 poland","eurosport 1 poland",
        "eurosport 2 poland","tvp","tvn","motowizja","filmbox premium","hbo poland","mtv poland",
    ]):
        country = "Poland"
    elif "turkey" in n or " tr" in n or any(k in n for k in [
        "bein sports 1 turkey","bein sports 2 turkey","bein sports 3 turkey",
        "bein sports 4 turkey","bein sports 5 turkey","a spor","trt spor",
        "atv turkey","kanal d","show tv","star tv","now tv turkey","tv8 turkey",
    ]):
        country = "Turkey"
    elif "nl" in n or "netherland" in n or any(k in n for k in [
        "ziggo sport","espn 1 nl","espn 2 nl","espn 3 nl","eurosport 1 nl","eurosport 2 nl",
        "rtl7","veronica","sbs6",
    ]):
        country = "Netherlands"
    elif "brazil" in n or "brasil" in n or any(k in n for k in [
        "sportv","espn brasil","espn2 brasil","espn3 brasil","espn4 brasil",
        "combate brasil","premier brasil","tnt brasil","globo sp","globo rio","bandsports",
    ]):
        country = "Brazil"
    elif "argentina" in n or any(k in n for k in [
        "espn argentina","espn2 argentina","espn3 argentina","fox sports argentina",
        "fox sports 2 argentina","fox sports 3 argentina","tnt sports argentina","tyc sports",
    ]):
        country = "Argentina"
    elif "canada" in n or " ca" in n or any(k in n for k in [
        "tsn","sportsnet","rds","ctv","tva sports","global ca","cbc ca","noovo",
        "tvo ca","yes tv ca","ytv ca",
    ]):
        country = "Canada"
    elif "australia" in n or " au" in n or any(k in n for k in [
        "fox sports 502","fox sports 503","fox sports 504","fox sports 505",
        "fox sports 506","fox sports 507","bein sports australia","fox cricket",
    ]):
        country = "Australia"
    elif "romania" in n or any(k in n for k in [
        "digi sport","orange sport","prima sport","prima tv ro",
    ]):
        country = "Romania"
    elif "croatia" in n or any(k in n for k in [
        "sport klub","arena sport 1 croatia","arena sport 2 croatia","arena sport 3 croatia",
        "arena sport 4 croatia","max sport 1 croatia","max sport 2 croatia",
    ]):
        country = "Croatia"
    elif "serbia" in n or any(k in n for k in [
        "arena sport 1 serbia","arena sport 2 serbia","arena sport 3 serbia",
        "arena sport 4 serbia","arena sport 5 serbia","happy tv serbia",
        "nova s serbia","nova sport serbia",
    ]):
        country = "Serbia"
    elif "bulgaria" in n or any(k in n for k in [
        "diema","max sport 1 bulgaria","max sport 2 bulgaria","max sport 3 bulgaria",
        "max sport 4 bulgaria","nova sport bulgaria","bnt","btv","ring bulgaria",
        "fox hd bulgaria","nova tv bulgaria",
    ]):
        country = "Bulgaria"
    elif "greece" in n or any(k in n for k in [
        "cosmote sport","nova sports","eurosport 1 greece","eurosport 2 greece","ert 1",
    ]):
        country = "Greece"
    elif "israel" in n or any(k in n for k in [
        "sport 1 israel","sport 2 israel","sport 3 israel","sport 4 israel","sport 5",
        "one 1 hd","one 2 hd","channel 9 israel","channel 10","channel 11 israel",
        "channel 12 israel","channel 13 israel","channel 14 israel","hot3","yes movies",
    ]):
        country = "Israel"
    elif "denmark" in n or any(k in n for k in [
        "dr1","dr2","kanal 4","kanal 5","canal 9 denmark","tv2 bornholm","tv2 sport x",
        "tv3 sport","tv2 sport denmark","tv2 denmark","tv2 zulu","tv3+","6'eren",
        "tv3 max","see denmark","mtv denmark",
    ]):
        country = "Denmark"
    elif "sweden" in n or any(k in n for k in [
        "c more","v film","tv4 hockey","tv4 tennis","tv4 motor","tv4 sport",
        "tv4 football","v sport motor","eurosport 1 sw","eurosport 2 sw",
    ]):
        country = "Sweden"
    elif "uae" in n or any(k in n for k in ["abu dhabi","dubai sports","dubai racing"]):
        country = "UAE"
    elif "arabic" in n or "mena" in n or any(k in n for k in [
        "bein sports 1 arabic","alkass","ssc sport","ontime sports","bein sports max ar",
        "bein sports hd qatar",
    ]):
        country = "Arab"
    elif "nz" in n or "new zealand" in n or any(k in n for k in [
        "sky sport 1 nz","sky sport 2 nz","sky sport 3 nz","sky sport 4 nz",
        "sky sport 5 nz","sky sport 6 nz","sky sport 7 nz","sky sport 8 nz",
        "sky sport 9 nz","sky sport select nz",
    ]):
        country = "New Zealand"
    elif "mexico" in n or " mx" in n or any(k in n for k in [
        "azteca","fox sports 1 mx","fox sports 2 mx","fox sports 3 mx",
        "espn 1 mx","espn 2 mx","espn 3 mx","espn 4 mx","tudn mx","tvc deportes",
        "claro sports","canal5 mx","las estrellas",
    ]):
        country = "Mexico"
    elif "africa" in n or "afrique" in n or any(k in n for k in [
        "supersport","dstv","canal+ sport 1 afrique",
    ]):
        country = "Africa"
    elif "malaysia" in n or "astro" in n:
        country = "Malaysia"
    elif "pakistan" in n or " pk" in n:
        country = "Pakistan"
    elif "india" in n or " in" in n:
        country = "India"
    elif "ireland" in n:
        country = "Ireland"
    elif "russia" in n:
        country = "Russia"
    elif "cyprus" in n:
        country = "Cyprus"
    elif "hungary" in n:
        country = "Hungary"
    elif "cz" in n or "czech" in n:
        country = "Czech Republic"
    elif "sk" in n or "slovakia" in n:
        country = "Slovakia"
    elif "bih" in n or "bosnia" in n:
        country = "Bosnia"

    # Category detection
    category = "General"
    sport_keys = [
        "sport","espn","sky sport","bein","dazn","eurosport","arena sport","tennis",
        "golf","football","cricket","nba tv","nfl","mlb","nhl","f1","motogp","calcio",
        "laliga","bundesliga","premier league","movistar","racing","rugby",
        "motorsport","rally","pdc","wwe","combate","fight","polsat sport","cosmote sport",
        "nova sport","ziggo sport","supersport","sec network","acc network","big ten",
        "pac-12","canal+ foot","canal+ sport","rmc sport","l'equipe","ssc sport",
        "ontime","willow","astro super","alkass","racer","bandsports",
    ]
    news_keys = ["news","bfm","cnn","msnbc","fox news","cnbc","headline","newsmax",
                 "newsnation","c span","lci","cnews","fox business","fox weather"]
    cinema_keys = ["cinema","hbo","showtime","starz","cinemax","movie","film","mgm",
                   "tcm","hallmark","axn"]
    kids_keys = ["kid","cartoon","nick","disney","boomerang","teen"]
    docu_keys = ["discovery","national geographic","nat geo","history","science",
                 "smithsonian","animal planet","travel"]
    music_keys = ["music","mtv","vh1","fashion"]
    fun_keys = ["comedy","fun","adult swim"]

    if any(k in n for k in sport_keys):
        category = "Sport"
    elif any(k in n for k in news_keys):
        category = "News"
    elif any(k in n for k in cinema_keys):
        category = "Cinema"
    elif any(k in n for k in kids_keys):
        category = "Enfants"
    elif any(k in n for k in docu_keys):
        category = "Documentaire"
    elif any(k in n for k in music_keys):
        category = "Musique"
    elif any(k in n for k in fun_keys):
        category = "Divertissement"
    elif "18+" in n:
        category = "18+"

    return {"category": category, "country": country}


# Pre-computed catalog (with category + country) — built once at import time.
DADDY_CHANNELS: List[Dict[str, str]] = []
for _id, _name in RAW_CHANNELS:
    if _name.startswith("18+"):
        continue
    meta = _categorize(_name)
    DADDY_CHANNELS.append(
        {"id": _id, "name": _name, "category": meta["category"], "country": meta["country"]}
    )

DADDY_BY_ID: Dict[str, Dict[str, str]] = {c["id"]: c for c in DADDY_CHANNELS}

DADDY_COUNTRIES: List[str] = sorted({c["country"] for c in DADDY_CHANNELS})
DADDY_CATEGORIES: List[str] = sorted({c["category"] for c in DADDY_CHANNELS})


def daddy_embed_url(channel_id: str) -> str:
    """Direct upstream embed URL (iframe source)."""
    return f"https://daddylive.li/embed/stream.php?id={channel_id}&player=1&source=tv"
