/**
 * Country → ISO 3166-1 alpha-2 code mapping (lowercase) used to build
 * flagcdn.com URLs.
 *
 *   <img src={flagUrl("France")} /> → https://flagcdn.com/24x18/fr.png
 */

// Country names used across the app (Vavoo, DaddyTV, sports) → ISO code.
// Keys are matched case-insensitively and accept both English & French names.
const COUNTRY_TO_CODE = {
  france: "fr",
  germany: "de",
  allemagne: "de",
  italy: "it",
  italie: "it",
  spain: "es",
  espagne: "es",
  "united kingdom": "gb",
  uk: "gb",
  "royaume-uni": "gb",
  england: "gb",
  scotland: "gb",
  wales: "gb",
  ireland: "ie",
  irlande: "ie",
  "northern ireland": "gb",
  "united states": "us",
  usa: "us",
  "u.s.a.": "us",
  america: "us",
  "états-unis": "us",
  portugal: "pt",
  netherlands: "nl",
  "pays-bas": "nl",
  holland: "nl",
  belgium: "be",
  belgique: "be",
  switzerland: "ch",
  suisse: "ch",
  poland: "pl",
  pologne: "pl",
  russia: "ru",
  russie: "ru",
  turkey: "tr",
  turquie: "tr",
  romania: "ro",
  roumanie: "ro",
  greece: "gr",
  grèce: "gr",
  austria: "at",
  autriche: "at",
  sweden: "se",
  suède: "se",
  denmark: "dk",
  danemark: "dk",
  norway: "no",
  norvège: "no",
  finland: "fi",
  finlande: "fi",
  albania: "al",
  albanie: "al",
  arabia: "sa",
  "saudi arabia": "sa",
  "arabie saoudite": "sa",
  bulgaria: "bg",
  bulgarie: "bg",
  czech: "cz",
  "czech republic": "cz",
  czechia: "cz",
  tchéquie: "cz",
  croatia: "hr",
  croatie: "hr",
  hungary: "hu",
  hongrie: "hu",
  serbia: "rs",
  serbie: "rs",
  ukraine: "ua",
  india: "in",
  inde: "in",
  brazil: "br",
  brésil: "br",
  brasil: "br",
  mexico: "mx",
  mexique: "mx",
  argentina: "ar",
  argentine: "ar",
  canada: "ca",
  australia: "au",
  australie: "au",
  "new zealand": "nz",
  "nouvelle-zélande": "nz",
  japan: "jp",
  japon: "jp",
  china: "cn",
  chine: "cn",
  "south korea": "kr",
  "corée du sud": "kr",
  korea: "kr",
  iran: "ir",
  israel: "il",
  israël: "il",
  egypt: "eg",
  égypte: "eg",
  "south africa": "za",
  "afrique du sud": "za",
  morocco: "ma",
  maroc: "ma",
  algeria: "dz",
  algérie: "dz",
  tunisia: "tn",
  tunisie: "tn",
  qatar: "qa",
  uae: "ae",
  "united arab emirates": "ae",
  emirates: "ae",
  kuwait: "kw",
  koweït: "kw",
  bahrain: "bh",
  oman: "om",
  jordan: "jo",
  jordanie: "jo",
  lebanon: "lb",
  liban: "lb",
  syria: "sy",
  syrie: "sy",
  iraq: "iq",
  irak: "iq",
  pakistan: "pk",
  bangladesh: "bd",
  indonesia: "id",
  indonésie: "id",
  malaysia: "my",
  malaisie: "my",
  philippines: "ph",
  vietnam: "vn",
  thailand: "th",
  thaïlande: "th",
  singapore: "sg",
  singapour: "sg",
  taiwan: "tw",
  "hong kong": "hk",
  chile: "cl",
  chili: "cl",
  peru: "pe",
  pérou: "pe",
  colombia: "co",
  colombie: "co",
  venezuela: "ve",
  ecuador: "ec",
  équateur: "ec",
  uruguay: "uy",
  paraguay: "py",
  bolivia: "bo",
  bolivie: "bo",
  panama: "pa",
  cuba: "cu",
  "dominican republic": "do",
  "république dominicaine": "do",
  jamaica: "jm",
  jamaïque: "jm",
  "puerto rico": "pr",
  estonia: "ee",
  estonie: "ee",
  latvia: "lv",
  lettonie: "lv",
  lithuania: "lt",
  lituanie: "lt",
  belarus: "by",
  biélorussie: "by",
  moldova: "md",
  moldavie: "md",
  slovakia: "sk",
  slovaquie: "sk",
  slovenia: "si",
  slovénie: "si",
  iceland: "is",
  islande: "is",
  malta: "mt",
  malte: "mt",
  cyprus: "cy",
  chypre: "cy",
  luxembourg: "lu",
  liechtenstein: "li",
  monaco: "mc",
  andorra: "ad",
  andorre: "ad",
  "bosnia and herzegovina": "ba",
  bosnia: "ba",
  bosnie: "ba",
  macedonia: "mk",
  "north macedonia": "mk",
  macédoine: "mk",
  montenegro: "me",
  monténégro: "me",
  kosovo: "xk",
  armenia: "am",
  arménie: "am",
  azerbaijan: "az",
  azerbaïdjan: "az",
  georgia: "ge",
  géorgie: "ge",
  kazakhstan: "kz",
  uzbekistan: "uz",
  ouzbékistan: "uz",
  afghanistan: "af",
  nepal: "np",
  népal: "np",
  "sri lanka": "lk",
  myanmar: "mm",
  cambodia: "kh",
  cambodge: "kh",
  laos: "la",
  mongolia: "mn",
  mongolie: "mn",
  // Africa
  nigeria: "ng",
  kenya: "ke",
  ghana: "gh",
  ethiopia: "et",
  éthiopie: "et",
  uganda: "ug",
  ouganda: "ug",
  tanzania: "tz",
  tanzanie: "tz",
  senegal: "sn",
  sénégal: "sn",
  "ivory coast": "ci",
  "côte d'ivoire": "ci",
  "cote d'ivoire": "ci",
  cameroon: "cm",
  cameroun: "cm",
  zimbabwe: "zw",
  zambia: "zm",
  zambie: "zm",
  angola: "ao",
  mozambique: "mz",
  libya: "ly",
  libye: "ly",
  sudan: "sd",
  soudan: "sd",
};

/**
 * Returns the ISO 3166-1 alpha-2 (lowercase) code for a country name,
 * or null if unknown.
 */
export function countryToCode(country) {
  if (!country) return null;
  const k = String(country).trim().toLowerCase();
  if (!k) return null;
  // Direct hit
  if (COUNTRY_TO_CODE[k]) return COUNTRY_TO_CODE[k];
  // Try without punctuation/parens (e.g. "Spain (es)" or "USA (United States)")
  const cleaned = k.replace(/\(.*?\)/g, "").trim();
  if (cleaned && COUNTRY_TO_CODE[cleaned]) return COUNTRY_TO_CODE[cleaned];
  // Last try: take the part before " - " or comma
  const head = k.split(/[-,/]/)[0].trim();
  if (head && COUNTRY_TO_CODE[head]) return COUNTRY_TO_CODE[head];
  return null;
}

/**
 * Returns the flagcdn URL for the given country (or empty string if unknown).
 * Default size 24x18 (perfect for inline icons next to text).
 */
export function flagUrl(country, size = "24x18") {
  const code = countryToCode(country);
  if (!code) return "";
  // xk (Kosovo) isn't on flagcdn — fallback to globe icon by caller
  if (code === "xk") return "";
  return `https://flagcdn.com/${size}/${code}.png`;
}

/**
 * Returns the flagcdn URL at 2x DPR resolution (HiDPI).
 */
export function flagUrl2x(country, size = "24x18") {
  const code = countryToCode(country);
  if (!code) return "";
  if (code === "xk") return "";
  return `https://flagcdn.com/${size}/${code}.png 2x`;
}
